# Generated by Django 4.2.2 on 2023-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_alter_edificio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Negocio', 'Negocio')], max_length=30),
        ),
    ]
