# Generated by Django 4.2.2 on 2023-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_alter_edificio_ciudad_alter_edificio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Negocio', 'Negocio'), ('Público', 'Público')], max_length=30),
        ),
    ]
